blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('article_list', cache_page(60)(views.BlogListView.as_view()), name='blog_list'),
    path('', cache_page(60)(views.blog_main), name='main'),
    path('create_article/', views.BlogCreateView.as_view(), name='blog_create'),
    path('update_article/<int:pk>', views.BlogUpdateView.as_view(), name='blog_update'),
    path('article_detail/<int:pk>', cache_page(60)(views.BlogDetailView.as_view()), name='blog_detail'),
    path('delete_article/<int:pk>', views.BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter_app.urls', namespace='newsletter')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('blog/', include(('blog.urls', 'blog'),  namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

null_options = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    content = models.TextField(verbose_name='Контент статьи')
    photo = models.ImageField(upload_to='articles/photo')
    view_counter = models.IntegerField(default=0, verbose_name='количество просмотров')
    published_date = models.DateTimeField(auto_now=True, **null_options, verbose_name='дата публикации')

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

    def __str__(self):
        return f'{self.title} {self.view_counter} {self.published_date}'

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog

from users.forms import StyleFormMixin


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('view_counter',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView

from blog.models import Blog
from blog.forms import BlogForm


# Create your views here.

class BlogCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.add_blog'
    success_url = reverse_lazy('blog:main')


class BlogListView(ListView):
    model = Blog


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse('blog:blog_update', kwargs={'pk': self.object.pk})


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    permission_required = 'blog.delete_blog'


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['some_another_articles'] = Blog.objects.all()[:2]
        return context


def blog_main(request):
    view = []
    all_articles = Blog.objects.all().order_by("?")
    for article in all_articles:
        view.append(article.view_counter)
    top_views = max(view)
    some_another_articles = all_articles[:3]
    popular_article = all_articles.filter(view_counter=top_views).last()
    return render(request, 'blog/blog_main_page.html', {'popular_article': popular_article,
                                                        'some_another_articles': some_another_articles})

blog/templates/blog/blog_confirm_delete.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% block content %}
<div class="row mt-5 mb-5 pb-5 text-center">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    <h4 class="my-0 fw-normal d-inline">Удалить статью {{ object.title }} ?</h4>
                </div>
                <button type="submit" class="btn btn-danger mt-2 mb-2">
                    Удалить
                </button>
                 {% if object %}
                <a class="btn btn-primary mt-2 mb-2" href="{% url 'blog:blog_list' %}">Отмена</a>
                  {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% load my_tags %}
<main class="container">
    {% block content %}
<div class="dropdown mt-5 me-3 bd-mode-toggle position-absolute top-0 end-0">
    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Все статьи</a>
</div>
    <div class="container d-flex " style="flex-wrap: wrap; justify-content: space-around">
        {% for article in some_another_articles %}
        <div class="content col-3 mt-4 ms-1 me-1 border border-secondary rounded-3" style="overflow: hidden">
            <div class="content__header bg-secondary">
                <img width="100%" src="{{ article.photo | media_filter }}">
            </div>
            <div class="main__content ms-1">
                <h3>{{ article.title }}</h3>
                <hr>
                <p>{{ article.content | only_60 }}</p>
            </div>
            <a href="{% url 'blog:blog_detail' article.pk %}">Просмотреть</a>
        </div>
        {% endfor %}
    </div>
    <div class="content mt-3 ">
        <div class="content__header bg-secondary border border-secondary rounded-3 pt-2 pb-2 ps-2 pe-2">
            <img width="100%" src="{{ object.photo | media_filter }}">
        </div>
        <h3>{{ object.title }}</h3>
        <p>{{ object.view_counter }}</p>
        <hr>
        <p>{{ object.content }}</p>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% block content %}
<div class="row mt-5 mb-5 pb-5 text-center">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary mt-2 mb-2">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                 {% if object %}
                <a class="btn btn-primary mt-2 mb-2" href="{% url 'blog:blog_list' %}">К статьям</a>
                  {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% load my_tags %}
<main class="container">
{% block content %}
{% if perms.blog.add_blog %}
<div class="dropdown mt-5 me-3 bd-mode-toggle position-absolute top-0 end-0">

    <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Добавить статью</a>

</div>
{% endif %}
<div class="container d-flex " style="flex-wrap: wrap; justify-content: space-around">
    {% for object in object_list %}
    <div class="content col-3 mt-4 ms-1 me-1 border border-secondary rounded-3" style="overflow: hidden">
        <div class="content__header bg-secondary">
            <img width="100%"  src="{{ object.photo | media_filter }}">
        </div>
        <div class="main__content ms-1">
            <h3>{{ object.title }}</h3><hr>
            <p>{{ object.content | only_60 }}</p>

        </div>
        <div class="content__footer ms-1">
            <a href="{% url 'blog:blog_detail' object.pk %}">Просмотреть</a>
            {% if perms.blog.delete_blog and perms.blog.change_blog %}
            <a href="{% url 'blog:blog_update' object.pk %}">Изменить</a>
            <a href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>
            {% endif %}
        </div>

    </div>
    {% endfor %}
</div>
</main>
{% endblock %}

blog/templates/blog/blog_main_page.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% load my_tags %}
<main class="container">
    {% block content %}
<div class="dropdown mt-5 me-3 bd-mode-toggle position-absolute top-0 end-0">
    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Все статьи</a>
</div>
    <div class="container d-flex " style="flex-wrap: wrap; justify-content: space-around">
        {% for object in some_another_articles %}
        <div class="content col-3 mt-4 ms-1 me-1 border border-secondary rounded-3" style="overflow: hidden">
            <div class="content__header bg-secondary">
                <img width="100%" src="{{ object.photo | media_filter }}">
            </div>
            <div class="main__content ms-1">
                <h3>{{ object.title }}</h3>
                <hr>
                <p>{{ object.content | only_60 }}</p>
            </div>
            <a href="{% url 'blog:blog_detail' object.pk %}">Просмотреть</a>
        </div>
        {% endfor %}
    </div>
    <div class="content mt-3 ">
        <div class="content__header bg-secondary border border-secondary rounded-3 pt-2 pb-2 ps-2 pe-2">
            <img width="100%" src="{{ popular_article.photo | media_filter }}">
        </div>
        <h3>{{ popular_article.title }}</h3>
        <p>{{ popular_article.view_counter }}</p>
        <hr>
        <p>{{ popular_article.content }}</p>
    </div>
</main>
{% endblock %}