blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('article_list', cache_page(60)(views.BlogListView.as_view()), name='blog_list'),
    path('', cache_page(60)(views.blog_main), name='main'),
    path('create_article/', views.BlogCreateView.as_view(), name='blog_create'),
    path('update_article/<int:pk>', views.BlogUpdateView.as_view(), name='blog_update'),
    path('article_detail/<int:pk>', cache_page(60)(views.BlogDetailView.as_view()), name='blog_detail'),
    path('delete_article/<int:pk>', views.BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter_app.urls', namespace='newsletter')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('blog/', include(('blog.urls', 'blog'),  namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users import views

from users.apps import UsersConfig

name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', views.CreateUser.as_view(), name='registration'),
    path('confirm-email/<str:token>/', views.email_verification, name='email_confirm'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('user_delete/<int:pk>', views.DeleteUserView.as_view(), name='user_delete'),
    path('account_change/<int:pk>', views.ChangeUserView.as_view(), name='account_change'),
    path('user_active_button/<int:pk>', views.user_status, name='user_status_button'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.ResetComplete.as_view(), name='password-confirm'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
null_options = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **null_options)
    avatar = models.ImageField(upload_to='users/users_avatar', verbose_name='аватар', **null_options)
    token = models.CharField(max_length=100, verbose_name='токен', **null_options)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.forms import ModelForm, BooleanField
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, PasswordResetForm
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = "form-check-input"
            else:
                fild.widget.attrs['class'] = "form-control"


class UserRegistrationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'password1', 'password2',)


class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

users/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import (PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView, PasswordResetView)
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from users.models import User
from users.forms import UserRegistrationForm
from django.core.mail import send_mail
from config.settings import EMAIL_HOST_USER

import secrets

from users.services import make_random_password


# Create your views here.


class CreateUser(CreateView):
    model = User
    form_class = UserRegistrationForm

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/confirm-email/{token}/'
        send_mail(subject='Подтверждение пароля',
                  message=f'Для подтверждения перейдите по ссылке {url}',
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('newsletter_app:main_page')


class UserListView(PermissionRequiredMixin, ListView):
    permission_required = 'users.view_user'
    model = User


class ChangeUserView(UpdateView):
    model = User
    fields = ('email', 'first_name', 'last_name', 'phone')

    def get_success_url(self):
        return reverse('users:account_change', kwargs={'pk': self.object.pk})


class DeleteUserView(DeleteView):
    model = User
    success_url = reverse_lazy('newsletter_app:main_page')


class PasswordReset(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')

    def form_valid(self, form):
        if self.request.method == 'POST':
            user_email = self.request.POST.get('email')
            user = User.objects.filter(email=user_email).first()
            if user:
                new_password = make_random_password()
                user.set_password(new_password)
                user.save()
                try:
                    send_mail(
                        subject="Восстановление пароля",
                        message=f"Здравствуйте! Ваш пароль для доступа на наш сайт изменен:\n"
                                f"Данные для входа:\n"
                                f"Email: {user_email}\n"
                                f"Пароль: {new_password}",
                        from_email=EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )
                except Exception:
                    print(f'Ошибка пр отправке письма, {user.email}')
                return HttpResponseRedirect(reverse('users:password_reset_done'))


class PasswordResetConfirm(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password-confirm')


class PasswordResetDone(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class ResetComplete(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    if user:
        user.is_active = True
        user.save()
    else:
        return redirect(reverse('users:error_page'))
    return redirect(reverse('users:login'))


def user_status(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users'))

users/templates/users/password_reset_confirm.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% load i18n %}
{% block content %}
<main class="px-3 mt-5 mb-5 w-100" style="overflow: auto">
    <div class="row mt-5 mb-5 pb-5">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2 mb-2">
                       Сбросить пароль
                    </button>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% block content %}
{% load i18n %}
{% block userlinks %}
<main class="px-3 mt-5" style="height:30em">
    <h1>Ваш пароль успешно изменен</h1>
    <p> <a href="{% url 'newsletter_app:main_page' %}">На главную</a></p>
    <p class="lead">
        <a href="{% url 'users:login' %}">На страницу входа</a>
    </p>
</main>
  {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% translate 'Documentation' %}</a> / {% endif %}{% translate 'Change password' %} /
{% endblock %}
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
{% translate 'Your new password:' %} {{ user.password }}
{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% block content %}
<main class="px-3 mt-5 mb-5 w-100" style="overflow: auto">
    <div class="row mt-5 mb-5 pb-5">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2 mb-2">
                       Сбросить пароль
                    </button>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/passwrd_reset_complete.html
{% extends 'newsletter_app/base/outside_base.html' %}
{% load i18n %}
{% block content %}
<main class="px-3 mt-5 mb-5 w-100" style="overflow: auto">
    <div class="row mt-5 mb-5 pb-5">
        <div class="col-12">
            <div class="row">
                <div class="card">
                    <div class="card-body">
                        <p>Пароль успешно изменен</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'newsletter_app/base/inside_base.html' %}
{% block content %}
      <div class="container py-3" style=" overflow: auto; max-height: 70vh;">
        <div class="card mb-4 rounded-3 shadow-sm" style="max-width: 73%;">
            <div class="container">
              <div class="d-flex justify-content-between card-header py-3">
                  <div class="d-inline">
                    <h4 class="my-0 fw-normal d-inline">Удалить {{ object.first_name }} {{ object.last_name }}?</h4>
                  </div>
              </div>
            </div>
          <div class="card-body text-center">
              {% csrf_token %}
              <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
              <button type="submit" class="btn w-100 btn btn-lg btn-outline-primary fw-bold border-danger mt-2 mb-2">
                Подтвердить
              </button>
             <a class="btn w-100 btn btn-lg btn-outline-primary" href="{% url 'newsletter_app:message_detail' object.pk %}" role="button">Отмена</a>
             </form>
          </div>
        </div>
      </div>
{% endblock %}

users/templates/users/user_form.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script type="text/javascript" src="https://me.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=aoh58VZImFdvJyy2-boe_98uHsxsxjcLAn5unvzlmElLLfSTWesrFMduB_GmsXvF3zmPBSSZSf3cD1G3w5DTpyAnViIRuK2dRkevU15iaZ8" charset="UTF-8"></script><script src="{% static 'js/color-modes.js' %}"></script>

    {%include 'newsletter_app/includes/some_meta.html' %}

    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->

{%include 'newsletter_app/includes/some_links.html' %}

    {% include 'newsletter_app/includes/some_style.html' %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sign-in.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">

    {% include 'newsletter_app/includes/style_for_page.html' %}

    <div class="dropdown position-fixed bottom-0 end-0  mb-3 me-3 bd-mode-toggle">
    {% include 'newsletter_app/includes/light_button.html' %}
    </div>

<main class="form-signin w-100 m-auto">
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary mt-2 mb-2">
          {% if object %}
          Сохранить изменения
          {% else %}
          Зарегистрироваться
          {% endif %}
      </button>
  </form>
    <a class="btn btn-primary" href="{% url 'newsletter_app:home' %}">На главную</a>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

users/templates/users/user_list.html
{% extends 'newsletter_app/base/inside_base.html' %}
{% load text_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col" style="overflow: auto; max-height: 90vh;">
            <table class="table table-dark table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">ФИО</th>
                    <th scope="col">Email</th>
                    <th scope="col">Статус</th>
                </tr>
                </thead>
                {% for object in object_list %}
                <tbody>
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url 'newsletter_app:client_detail' object.pk %}">{{ object.email }}</a></td>
                    <td><a href="{% url 'newsletter_app:client_detail' object.pk %}">{{ object.phone }}</a></td>
                    {% if object.is_active %}
                    <td><a class="btn btn-primary" href="{% url 'users:user_status_button' object.pk %}">Отключить</a></td>
                    {% else %}
                    <td><a class="btn btn-primary" href="{% url 'users:user_status_button' object.pk %}">Активировать</a></td>
                    {% endif %}
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}